### PR TITLE
fix: center bottom text

### PR DESCRIPTION
**Pull request by c0rydoras**
center bottom text

### CODE REVIEW

**Review by gianklug — COMMENTED** [review]
why `text-center` twice?

**Comment by c0rydoras** [comment]
Probably hit the wrong button on my keyboard

**Comment by c0rydoras** [comment]
@gianklug this should be fixed now

**Comment by gianklug** [comment]
> @gianklug this should be fixed now

no need to ping people, thanks.

**Review by gianklug — APPROVED** [review]
LGTM

**Pull request merged**
